version: '3.7'
services:

  # node:
  #   container_name: node
  #   image: node:14-alpine
  #   ports:
  #   - "3000:3000"
  #   volumes:
  #     - ./server:/usr/src/app
  #   networks:
  #     - app-net

  mongo:
    container_name: mongo
    image: mongo:4.4
    # command: --smallfiles
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./temp/data/db:/data/db
    networks:
      - app-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    depends_on:
      - mongo
    networks:
      - app-net

networks: #----------------------------------------------
  app-net:
    name: app-net
    driver: bridge
